version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:v1.4.4
    ports:
      - "8080:80"
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:v1.4.4
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb
  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      UPLOAD_LIMIT: 2048M
      MEMORY_LIMIT: 2048M
      MAX_EXECUTION_TIME: 600
      PMA_HOST: phpipam-mariadb
    restart: always
    ports:
      - '8081:80'
    links:
      - phpipam-mariadb
    depends_on:
      - phpipam-mariadb

volumes:
  phpipam-db-data:
  phpipam-logo:
